### ISSUE TITLE
[bug] Can't open web3modal with an active WalletConnect session

### ISSUE THREAD

**Issue by csmartinsfct** [WalletConnect/web3modal#1240]
### Link to minimal reproducible example

https://github.com/csmartinsfct/wallet-connect-no-modal

### Summary

Steps to reproduce:

- launch app
- connect to Uniswap by inputing the wallet connect URI, thus creating a session.
- click the "open modal" button at the top

Modal does not open. 

- Clear app's storage.
- Refresh app.
- click the "open modal" button at the top

Modal opens.

Here is a GIF showcasing the issue:

I open the app with a clean local storage, connect to Uniswap, try to open the modal and it doesn't open. Clear the storage, refresh, try to open the modal and it opens.

![2023-08-01 12 51 56](https://github.com/WalletConnect/web3modal/assets/24925905/cda155d5-cf26-4a66-a58d-f28df11caecd)

### List of related npm package versions

"@walletconnect/utils": "2.9.1",
"@walletconnect/web3wallet": "1.8.7",
"@web3modal/ethereum": "^2.7.1",
"@web3modal/react": "^2.7.1",
"ethers": "5.6.6",
"wagmi": "^1.3.9"

In another app where I have this integrated I see this error on startup if I have any active sessions:

```Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at H (https://local-app.meld.com:3000/static/js/bundle.js:180382:17)
    at Sa (https://local-app.meld.com:3000/static/js/vendors-node_modules_walletconnect_ethereum-provider_dist_index_es_js.chunk.js:8687:75)
    at Yg (https://local-app.meld.com:3000/static/js/vendors-node_modules_walletconnect_ethereum-provider_dist_index_es_js.chunk.js:8680:13)
    at https://local-app.meld.com:3000/static/js/vendors-node_modules_walletconnect_ethereum-provider_dist_index_es_js.chunk.js:9287:13
    at Array.forEach (<anonymous>)
    at hr.createProviders (https://local-app.meld.com:3000/static/js/vendors-node_modules_walletconnect_ethereum-provider_dist_index_es_js.chunk.js:9283:114)
    at hr.checkStorage (https://local-app.meld.com:3000/static/js/vendors-node_modules_walletconnect_ethereum-provider_dist_index_es_js.chunk.js:9263:81)
    at async hr.initialize (https://local-app.meld.com:3000/static/js/vendors-node_modules_walletconnect_ethereum-provider_dist_index_es_js.chunk.js:9267:66)
    at async hr.init (https://local-app.meld.com:3000/static/js/vendors-node_modules_walletconnect_ethereum-provider_dist_index_es_js.chunk.js:9167:12)
    at async v.initialize (https://local-app.meld.com:3000/static/js/vendors-node_modules_walletconnect_ethereum-provider_dist_index_es_js.chunk.js:264:145)
    at async v.init (https://local-app.meld.com:3000/static/js/vendors-node_modules_walletconnect_ethereum-provider_dist_index_es_js.chunk.js:100:12)
    at async WalletConnectConnector.initProvider_fn (https://local-app.meld.com:3000/static/js/bundle.js:510353:87)```

**Comment by 0xAsimetriq** [comment]
What are you trying to achieve? Atm it looks like you are adding modal (dapp sdk) into a wallet, which will likely not work / have storage conflicts. Also, wagmi > 1 no longer compatible with ethers, they use their own library now https://viem.sh/

**Comment by 0xAsimetriq** [comment]
Just a small update on this, we investigated and this will need a bit of core work done on our end (clients in `walletconnect-monorepo`) to decouple storages for different sdks i.e. ones you use as a wallet and as a dapp with web3modal, will let you know when this is available.

**Comment by enesozturk** [comment]
Hey there, seems like it's been months after this issue and we have v3 of web3modal, which is our main focus and actively iterating. Soon, we're planning to gradually drop the support for the v1 and v2. 

@csmartinsfct, if you still building your app, we'd encourage you to upgrade to v3 by following the steps in our documentation, and let us know if you encounter any issues. We're ready to help anytime.

- https://docs.walletconnect.com/web3modal/about
