### ISSUE TITLE
[bug] Unable to build with react vite.js 

### ISSUE THREAD

**Issue by dellwatson** [WalletConnect/web3modal#1502]
### Link to minimal reproducible example

[1st_reproducible_V3/examples/react-wagmi](https://github.com/WalletConnect/web3modal/blob/V3/examples/react-wagmi) 
[2nd_reproducible_repo](https://github.com/dellwatson/web3modal-vite)

### Summary

This issue is on vite build, while it does running on localhost but it unable to build the app. 
i thought it was my own app problem but you can find it in this git repo example too, try to `npm run build:example` and it will encounter this issue. 

<img width="982" alt="Screenshot 2023-11-23 at 11 31 02 AM" src="https://github.com/WalletConnect/web3modal/assets/13269454/f3fde70c-24a4-4d64-a933-7a28f8944bda">

```js
> @examples/react-wagmi@3.3.2 build:examples
> vite build

vite v4.5.0 building for production...
✓ 4 modules transformed.
✓ built in 46ms
[vite]: Rollup failed to resolve import "@web3modal/wagmi/react" from "/Users/dellwatson/Desktop/hackthons/web3modal/examples/react-wagmi/src/App.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@web3modal/wagmi/react" from "/Users/dellwatson/Desktop/hackthons/web3modal/examples/react-wagmi/src/App.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///Users/dellwatson/Desktop/hackthons/web3modal/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48216:27)
    at onwarn (/Users/dellwatson/Desktop/hackthons/web3modal/node_modules/@vitejs/plugin-react/dist/index.cjs:255:9)
    at onRollupWarning (file:///Users/dellwatson/Desktop/hackthons/web3modal/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48245:9)
    at onwarn (file:///Users/dellwatson/Desktop/hackthons/web3modal/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:47976:13)
    at file:///Users/dellwatson/Desktop/hackthons/web3modal/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file:///Users/dellwatson/Desktop/hackthons/web3modal/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/dellwatson/Desktop/hackthons/web3modal/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file:///Users/dellwatson/Desktop/hackthons/web3modal/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! Lifecycle script `build:examples` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @examples/react-wagmi@3.3.2 
npm ERR!   at location: /Users/dellwatson/Desktop/hackthons/web3modal/examples/react-wagmi 
```

and i did try some polyfill but it's not working either :
```js

  build: {
    rollupOptions: {
      plugins: [
        // require("@rollup/plugin-json")(),
        require("@rollup/plugin-node-resolve")({
          // Specify the 'json' option to resolve JSON files
          json: true,
        }),
      ],
    },
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },
  ```

### List of related npm package versions

nodejs: v18.14.1

i did try all of these package versions:
"@web3modal/wagmi": "3.3.2"|
    "@web3modal/wagmi": "^3.2.1",

    "wagmi": "^1.4.7",
    "wagmi": "^1.3.10",

    "vite": "^4.4.5"
        "vite": "^5.0.2"
    "@vitejs/plugin-react": "^4.0.3",

**Comment by glitch-txs** [comment]
Hi, thanks for reporting, please provide a minimal reproducible example of the issue, if possible a public repository or code sandbox, closing in the meantime 👌

**Comment by dellwatson** [comment]
@glitch-txs this is the minimal reproducible:[https://github.com/WalletConnect/web3modal/blob/V3/examples/react-wagmi]( https://github.com/WalletConnect/web3modal/blob/V3/examples/react-wagmi)
exactly from your example. 

it cannot be build, and using sandbox would be pointless since it's local development

**Comment by glitch-txs** [comment]
@dellwatson could you remove node_modules folder from the example?
gitignore file should start with . instead of _

**Comment by dellwatson** [comment]
@glitch-txs yes done now with gitignore , no idea why it goes with _

**Comment by dellwatson** [comment]
imnot sure with issue, i change wagmi v1.4.6 to 1.4.7 and solve the issue
