### ISSUE TITLE
[bug] Web3 modal issues with switch network on mobile wallet

### ISSUE THREAD

**Issue by maksymKhaiuk1989** [WalletConnect/web3modal#2042]
### Link to minimal reproducible example

https://web3modal.com/

### Summary

Switch network on mobile is not stable, sometimes its not working at all, some times its not synchronized with website and wallet. 

https://github.com/WalletConnect/web3modal/assets/147406081/93c88334-a998-43f2-b84a-fddbd562eeb2

I tested newest versions 4.0.13 and 4.1.0 aswell, and it is even more buggy than version used on your website. 
Here is list of bugs which i discovered:
1. You can't disable required chain, 
```
createWeb3Modal({
  wagmiConfig,
  projectId: appConfig.walletConnectProjectId,
  includeWalletIds: SUPPORTED_WALLETS_IDS,
  allowUnsupportedChain: true,
  defaultChain: appConfig.env === 'production' ? polygon : devChain,
});
```
with allowUnsupported chain = true, you can't connect at all, here is the error 
```
useAuth.tsx:69 SwitchChainError: An error occurred when attempting to switch chain.

Details: Chain not configured.

Version: @wagmi/core@2.6.5
Version: viem@2.7.22
    at Object.switchChain (walletConnect.js:163:23)
    at Object.getProvider (walletConnect.js:132:41)
    at getConnectorClient (getConnectorClient.js:40:50)
    at signMessage (signMessage.js:23:98)
    at Object.mutationFn (signMessage.js:13:88)
    at Object.fn (mutation.js:75:31)
    at run (retryer.js:93:31)
    at createRetryer (retryer.js:126:5)
    at executeMutation (mutation.js:70:81)
    at Mutation.execute (mutation.js:109:26)
    at async generateSignature (useAuth.tsx:64:7)
```

2. If i set default chain on mobile after i connect my wallet the whole screen gets covered with empty web3modal overlay, and there is no any message in metamask mobile wallet.
<img width="1261" alt="screen" src="https://github.com/WalletConnect/web3modal/assets/147406081/1f7ef577-3774-4523-adf9-e4ff1aa88515">

### List of related npm package versions

    "@web3modal/core": "^4.1.0",
    "@web3modal/wagmi": "^4.1.0",
    "next": "^13.5.6",
    "react": "^18.2.0",
    "viem": "^2.7.22",
    "wagmi": "^2.5.7"

**Comment by glitch-txs** [comment]
> Switch network on mobile is not stable, sometimes its not working at all, some times its not synchronized with website and wallet.
This is an issue on the MetaMask side and it's being fixed at the moment.

We'll check on the rest

cc @svenvoskamp @tomiir

**Comment by eth-nft** [comment]
Yes I confirm, both problems exist.

> If i set default chain on mobile after i connect my wallet the whole screen gets covered with empty web3modal overlay, and there is no any message in metamask mobile wallet.

According to my observations, this problem only exists on mobile devices.
To reproduce this problem, in the metamask select the wrong chain, for example the one that you did not transfer to wagmi config

And pass  `allowUnsupportedChain: false` property to createWeb3Modal function

`createWeb3Modal({
  wagmiConfig: config,
  projectId,
  enableAnalytics: true,
  enableOnramp: true
  allowUnsupportedChain: false,
})`

In DOM
![image](https://github.com/WalletConnect/web3modal/assets/106334035/8b86ec4a-7c5d-4de4-b453-8c68025a1f3b)

**Comment by toufique-imam** [comment]
is this fixed? as facing this issue.

**Comment by mmarinovic** [comment]
This is still a problem. Any updates?

**Comment by glitch-txs** [comment]
This is a MetaMask issue and should be reported in their repository
