### ISSUE TITLE
How can I get Web3Modal to render in storybook?

### ISSUE THREAD

**Issue by soltoshi** [WalletConnect/web3modal#373]
I've added a dependency on `web3modal` in my React project. However, when I try to start storybook, it breaks. Wondering if anyone has been able to get `Web3Modal` rendered in storybook?

Logs
```
[21:00:44] berkeley:holon-fe λ yarn storybook
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
yarn run v1.19.2
$ start-storybook -p 6006 -s public
info @storybook/react v6.4.9
info
(node:76964) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Serving static files from ./public at /
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack5 setup
1% setup initializeinfo => Using prebuilt manager
<i> [webpack-dev-middleware] wait until bundle finished
99% done plugins webpack-hot-middlewarewebpack built preview adf1f38f66f2201b6dfc in 12702ms
ModuleNotFoundError: Module not found: Error: Can't resolve 'stream' in '/Users/berkeley/holon/holon-fe/node_modules/cipher-base'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }
    at /Users/berkeley/holon/holon-fe/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/berkeley/holon/holon-fe/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/berkeley/holon/holon-fe/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/berkeley/holon/holon-fe/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/berkeley/holon/holon-fe/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/berkeley/holon/holon-fe/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/berkeley/holon/holon-fe/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/berkeley/holon/holon-fe/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/berkeley/holon/holon-fe/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/berkeley/holon/holon-fe/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/berkeley/holon/holon-fe/node_modules/neo-async/async.js:6883:13
    at /Users/berkeley/holon/holon-fe/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/Users/berkeley/holon/holon-fe/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/berkeley/holon/holon-fe/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/berkeley/holon/holon-fe/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/berkeley/holon/holon-fe/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
```

**Comment by 0xAsimetriq** [comment]
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.
