### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by justinhenricks** [WalletConnect/web3modal#551]
When I am running npm run build on a fresh pull, I am getting this error:

/Users/justin/Workspace/web3modal/node_modules/loader-runner/lib/LoaderRunner.js:133
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/justin/Workspace/web3modal/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/justin/Workspace/web3modal/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/justin/Workspace/web3modal/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/justin/Workspace/web3modal/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/justin/Workspace/web3modal/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/justin/Workspace/web3modal/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/justin/Workspace/web3modal/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/justin/Workspace/web3modal/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/justin/Workspace/web3modal/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/justin/Workspace/web3modal/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at makeSourceMapAndFinish (/Users/justin/Workspace/web3modal/node_modules/ts-loader/dist/index.js:88:5)
    at successLoader (/Users/justin/Workspace/web3modal/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/Users/justin/Workspace/web3modal/node_modules/ts-loader/dist/index.js:22:12)
    at LOADER_EXECUTION (/Users/justin/Workspace/web3modal/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/justin/Workspace/web3modal/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/justin/Workspace/web3modal/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/justin/Workspace/web3modal/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/justin/Workspace/web3modal/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/justin/Workspace/web3modal/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/justin/Workspace/web3modal/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Steps to reproduce:
1. pull the repo
2. npm run install

build fails

**Comment by justinhenricks** [comment]
Sorry duplicate .. https://github.com/webpack/webpack/issues/14532
